### ISSUE TITLE
잘봤습니다. 유익합니다. 

### ISSUE THREAD

**Issue by bcmbf14** [iamchiwon/Closure_ARC_Experiment#2]
- 소스1의 커밋 1번

소스는 3초인데 프린트는 5초네요 ㅎㅎ 

별거아니라 이해하기는 어렵지 않지만, 바꿔도 나쁘지 않을 것 같기도 합니다^^; 

잘봤습니다.

**Comment by iamchiwon** [comment]
아... 그렇네요. 5초로 했다가 너무 길어서 3초로 줄였었는데, 프린트는 고치지 않았네요.
별 의미는 없으니 수정하지 않겠습니다.
감사합니다.

**Comment by iamchiwon** [comment]
그냥 넘어가려 했으나, README 에만 수정하고 소스는 수정하지 않았습니다.

**Comment by bcmbf14** [comment]
😁
